
DROP TABLE IF EXISTS bijins;
CREATE TABLE bijins (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  bijin_id BIGINT UNSIGNED NOT NULL,
  link VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  thumb VARCHAR(255) NOT NULL,
  status INT DEFAULT 0,
  modified TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP NOT NULL,

  UNIQUE KEY(bijin_id),
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
